# Generated by Django 5.1.2 on 2024-12-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newcity",
            name="notes",
            field=models.TextField(max_length=200),
        ),
    ]
