# Generated by Django 5.1.4 on 2024-12-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_newcity_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcity',
            name='date',
            field=models.DateField(),
        ),
    ]
